import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import tz from 'dayjs/plugin/timezone';

dayjs.extend(utc);
dayjs.extend(tz);

export const TIMEZONE_LABELS: Record<string, string> = {
  'America/Los_Angeles': 'Pacific Time (US & Canada)',
  'America/Denver': 'Mountain Time (US & Canada',
  'America/Chicago': 'Central Time (US & Canada',
  'America/New_York': 'Eastern Time (US & Canada',

  'America/Adak': 'Adak, Alaska',
  'America/Anchorage': 'Anchorage, Alaska',
  'America/Boise': 'Boise, Idaho',
  'America/Phoenix': 'Phoenix, Arizona',
  'America/Detroit': 'Detroit, Michigan',
  'America/Indianapolis': 'Indianapolis, Indiana',
  'America/Indiana/Knox': 'Knox, Indiana',
  'America/Indiana/Marengo': 'Marengo, Indiana',
  'America/Indiana/Petersburg': 'Petersburg, Indiana',
  'America/Indiana/Tell_City': 'Tell City, Indiana',
  'America/Indiana/Vevay': 'Vevay, Indiana',
  'America/Indiana/Vincennes': 'Vincennes, Indiana',
  'America/Indiana/Winamac': 'Winamac, Indiana',
  'America/Louisville': 'Louisville, Kentucky',
  'America/Kentucky/Monticello': 'Monticello, Kentucky',
  'America/North_Dakota/Beulah': 'Beulah, North Dakota',
  'America/North_Dakota/Center': 'Center, North Dakota',
  'America/North_Dakota/New_Salem': 'New Salem, North Dakota',
  'America/Menominee': 'Menominee, Michigan',
  'America/Metlakatla': 'Metlakatla, Alaska',
  'America/Nome': 'Nome, Alaska',
  'America/Juneau': 'Juneau, Alaska',
  'America/Sitka': 'Sitka, Alaska',
  'America/Yakutat': 'Yakutat, Alaska',

  'America/Vancouver': 'Vancouver, British Columbia',
  'America/Whitehorse': 'Whitehorse, Yukon',
  'America/Dawson': 'Dawson, Yukon',
  'America/Dawson_Creek': 'Dawson Creek, British Columbia',
  'America/Fort_Nelson': 'Fort Nelson, British Columbia',
  'America/Creston': 'Creston, British Columbia',
  'America/Edmonton': 'Edmonton, Alberta',
  'America/Cambridge_Bay': 'Cambridge Bay, Nunavut',
  'America/Inuvik': 'Inuvik, Northwest Territories',
  'America/Regina': 'Regina, Saskatchewan',
  'America/Swift_Current': 'Swift Current, Saskatchewan',
  'America/Winnipeg': 'Winnipeg, Manitoba',
  'America/Rankin_Inlet': 'Rankin Inlet, Nunavut',
  'America/Resolute': 'Resolute, Nunavut',
  'America/Coral_Harbour': 'Coral Harbour, Nunavut',
  'America/Toronto': 'Toronto, Ontario',
  'America/Iqaluit': 'Iqaluit, Nunavut',
  'America/Moncton': 'Montreal, Quebec',
  'America/Halifax': 'Halifax, Nova Scotia',
  'America/Glace_Bay': 'Glace Bay, Nova Scotia',
  'America/Goose_Bay': 'Goose Bay, Newfoundland and Labrador',
  'America/Blanc-Sablon': 'Blanc-Sablon, Quebec',
  'America/St_Johns': "St. John's, Newfoundland",

  'America/Tijuana': 'Tijuana, Baja California',
  'America/Hermosillo': 'Hermosillo, Sonora',
  'America/Mazatlan': 'Mazatlan, Sinaloa',
  'America/Chihuahua': 'Chihuahua, Chihuahua',
  'America/Ojinaga': 'Ojinaga, Chihuahua',
  'America/Ciudad_Juarez': 'Ciudad Juarez, Chihuahua',
  'America/Monterrey': 'Monterrey, Nuevo Leon',
  'America/Matamoros': 'Matamoros, Tamaulipas',
  'America/Mexico_City': 'Mexico City',
  'America/Bahia_Banderas': 'Bahia Banderas, Nayarit',
  'America/Merida': 'Merida, Yucatan',
  'America/Cancun': 'Cancun, Quintana Roo',

  'America/Belize': 'Belize City, Belize',
  'America/Guatemala': 'Guatemala City, Guatemala',
  'America/Tegucigalpa': 'Tegucigalpa, Honduras',
  'America/El_Salvador': 'San Salvador, El Salvador',
  'America/Managua': 'Managua, Nicaragua',
  'America/Costa_Rica': 'San Jose, Costa Rica',
  'America/Panama': 'Panama City, Panama',

  'America/Havana': 'Havana, Cuba',
  'America/Nassau': 'Nassau, Bahamas',
  'America/Grand_Turk': 'Grand Turk, Turks and Caicos',
  'America/Jamaica': 'Kingston, Jamaica',
  'America/Cayman': 'George Town, Cayman Islands',
  'America/Port-au-Prince': 'Port-au-Prince, Haiti',
  'America/Santo_Domingo': 'Santo Domingo, Dominican Republic',
  'America/Puerto_Rico': 'San Juan, Puerto Rico',
  'America/Anguilla': 'Anguilla',
  'America/Antigua': 'Antigua and Barbuda',
  'America/Montserrat': 'Montserrat',
  'America/Guadeloupe': 'Guadeloupe',
  'America/Dominica': 'Dominica',
  'America/Martinique': 'Martinique',
  'America/St_Lucia': 'St. Lucia',
  'America/St_Vincent': 'St. Vincent and the Grenadines',
  'America/Barbados': 'Barbados',
  'America/Grenada': 'Grenada',
  'America/Port_of_Spain': 'Port of Spain, Trinidad and Tobago',
  'America/St_Kitts': 'St. Kitts and Nevis',
  'America/St_Barthelemy': 'St. Barthelemy',
  'America/Lower_Princes': 'St. Maarten',
  'America/Marigot': 'St. Martin',
  'America/Aruba': 'Aruba',
  'America/Curacao': 'Curacao',
  'America/Kralendijk': 'Kralendijk, Bonaire',
  'America/Tortola': 'Tortola, British Virgin Islands',
  'America/St_Thomas': 'St. Thomas, US Virgin Islands',

  'America/Caracas': 'Caracas, Venezuela',
  'America/Guyana': 'Georgetown, Guyana',
  'America/Paramaribo': 'Paramaribo, Suriname',
  'America/Cayenne': 'Cayenne, French Guiana',
  'America/Bogota': 'Bogota, Colombia',
  'America/Guayaquil': 'Guayaquil, Ecuador',
  'America/Lima': 'Lima, Peru',
  'America/La_Paz': 'La Paz, Bolivia',
  'America/Manaus': 'Manaus, Brazil',
  'America/Boa_Vista': 'Boa Vista, Brazil',
  'America/Porto_Velho': 'Porto Velho, Brazil',
  'America/Rio_Branco': 'Rio Branco, Brazil',
  'America/Eirunepe': 'Eirunepe, Brazil',
  'America/Cuiaba': 'Cuiaba, Brazil',
  'America/Campo_Grande': 'Campo Grande, Brazil',
  'America/Santarem': 'Santarem, Brazil',
  'America/Araguaina': 'Araguaina, Brazil',
  'America/Belem': 'Belem, Brazil',
  'America/Fortaleza': 'Fortaleza, Brazil',
  'America/Recife': 'Recife, Brazil',
  'America/Maceio': 'Maceio, Brazil',
  'America/Bahia': 'Bahia, Brazil',
  'America/Sao_Paulo': 'Sao Paulo, Brazil',
  'America/Santiago': 'Santiago, Chile',
  'America/Punta_Arenas': 'Punta Arenas, Chile',
  'America/Asuncion': 'Asuncion, Paraguay',
  'America/Buenos_Aires': 'Buenos Aires, Argentina',
  'America/Cordoba': 'Cordoba, Argentina',
  'America/Jujuy': 'Jujuy, Argentina',
  'America/Argentina/Tucuman': 'Tucuman, Argentina',
  'America/Catamarca': 'Catamarca, Argentina',
  'America/Argentina/La_Rioja': 'La Rioja, Argentina',
  'America/Argentina/San_Juan': 'San Juan, Argentina',
  'America/Mendoza': 'Mendoza, Argentina',
  'America/Argentina/San_Luis': 'San Luis, Argentina',
  'America/Argentina/Rio_Gallegos': 'Rio Gallegos, Argentina',
  'America/Argentina/Ushuaia': 'Ushuaia, Argentina',
  'America/Argentina/Salta': 'Salta, Argentina',
  'America/Montevideo': 'Montevideo, Uruguay',
  'America/Coyhaique': 'Coyhaique, Chile',
  'America/Noronha': 'Noronha, Brazil',

  'America/Scoresbysund': 'Scoresbysund, Greenland',
  'America/Godthab': 'Nuuk, Greenland',
  'America/Miquelon': 'Miquelon, Saint Pierre and Miquelon',
  'America/Thule': 'Thule, Greenland',
  'America/Danmarkshavn': 'Danmarkshavn, Greenland',
  'Atlantic/Azores': 'Azores, Portugal',
  'Atlantic/Cape_Verde': 'Cape Verde',
  'Atlantic/South_Georgia': 'South Georgia',
  'Atlantic/Stanley': 'Stanley, Falkland Islands',
  'Atlantic/Bermuda': 'Bermuda',
  'Atlantic/St_Helena': 'St. Helena',

  'Atlantic/Reykjavik': 'Reykjavik, Iceland',
  'Europe/Dublin': 'Dublin, Ireland',
  'Europe/London': 'London, United Kingdom',
  'Europe/Lisbon': 'Lisbon, Portugal',
  'Atlantic/Madeira': 'Madeira, Portugal',
  'Atlantic/Canary': 'Canary Islands, Spain',
  'Atlantic/Faeroe': 'Faroe Islands, Denmark',
  'Europe/Guernsey': 'Guernsey',
  'Europe/Jersey': 'Jersey',
  'Europe/Isle_of_Man': 'Isle of Man',
  'Europe/Paris': 'Paris, France',
  'Europe/Brussels': 'Brussels, Belgium',
  'Europe/Amsterdam': 'Amsterdam, Netherlands',
  'Europe/Luxembourg': 'Luxembourg',
  'Europe/Monaco': 'Monaco',
  'Europe/Berlin': 'Berlin, Germany',
  'Europe/Zurich': 'Zurich, Switzerland',
  'Europe/Vaduz': 'Vaduz, Liechtenstein',
  'Europe/Rome': 'Rome, Italy',
  'Europe/Vatican': 'Vatican City',
  'Europe/San_Marino': 'San Marino',
  'Europe/Madrid': 'Madrid, Spain',
  'Europe/Andorra': 'Andorra',
  'Europe/Gibraltar': 'Gibraltar',
  'Europe/Malta': 'Malta',
  'Europe/Vienna': 'Vienna, Austria',
  'Europe/Prague': 'Prague, Czech Republic',
  'Europe/Bratislava': 'Bratislava, Slovakia',
  'Europe/Budapest': 'Budapest, Hungary',
  'Europe/Ljubljana': 'Ljubljana, Slovenia',
  'Europe/Zagreb': 'Zagreb, Croatia',
  'Europe/Sarajevo': 'Sarajevo, Bosnia and Herzegovina',
  'Europe/Podgorica': 'Podgorica, Montenegro',
  'Europe/Belgrade': 'Belgrade, Serbia',
  'Europe/Skopje': 'Skopje, North Macedonia',
  'Europe/Tirane': 'Tirana, Albania',
  'Europe/Warsaw': 'Warsaw, Poland',
  'Europe/Copenhagen': 'Copenhagen, Denmark',
  'Europe/Stockholm': 'Stockholm, Sweden',
  'Europe/Oslo': 'Oslo, Norway',
  'Arctic/Longyearbyen': 'Longyearbyen, Svalbard',
  'Europe/Mariehamn': 'Mariehamn, Aland Islands',
  'Europe/Busingen': 'Busingen, Germany',
  'Europe/Bucharest': 'Bucharest, Romania',
  'Europe/Chisinau': 'Chisinau, Moldova',
  'Europe/Sofia': 'Sofia, Bulgaria',
  'Europe/Athens': 'Athens, Greece',
  'Europe/Nicosia': 'Nicosia, Cyprus',
  'Europe/Helsinki': 'Helsinki, Finland',
  'Europe/Tallinn': 'Tallinn, Estonia',
  'Europe/Riga': 'Riga, Latvia',
  'Europe/Vilnius': 'Vilnius, Lithuania',
  'Europe/Kiev': 'Kiev, Ukraine',
  'Europe/Simferopol': 'Simferopol, Ukraine',
  'Europe/Istanbul': 'Istanbul, Turkey',
  'Europe/Kaliningrad': 'Kaliningrad, Russia',
  'Europe/Minsk': 'Minsk, Belarus',
  'Europe/Moscow': 'Moscow, Russia',
  'Europe/Kirov': 'Kirov, Russia',
  'Europe/Volgograd': 'Volgograd, Russia',
  'Europe/Astrakhan': 'Astrakhan, Russia',
  'Europe/Saratov': 'Saratov, Russia',
  'Europe/Ulyanovsk': 'Ulyanovsk, Russia',
  'Europe/Samara': 'Samara, Russia',

  'Africa/Casablanca': 'Casablanca, Morocco',
  'Africa/El_Aaiun': 'El Aaiun, Western Sahara',
  'Africa/Abidjan': 'Abidjan, Ivory Coast',
  'Africa/Accra': 'Accra, Ghana',
  'Africa/Bamako': 'Bamako, Mali',
  'Africa/Banjul': 'Banjul, Gambia',
  'Africa/Bissau': 'Bissau, Guinea-Bissau',
  'Africa/Conakry': 'Conakry, Guinea',
  'Africa/Dakar': 'Dakar, Senegal',
  'Africa/Freetown': 'Freetown, Sierra Leone',
  'Africa/Lome': 'Lome, Togo',
  'Africa/Monrovia': 'Monrovia, Liberia',
  'Africa/Nouakchott': 'Nouakchott, Mauritania',
  'Africa/Ouagadougou': 'Ouagadougou, Burkina Faso',
  'Africa/Sao_Tome': 'Sao Tome, Sao Tome and Principe',
  'Africa/Algiers': 'Algiers, Algeria',
  'Africa/Bangui': 'Bangui, Central African Republic',
  'Africa/Brazzaville': 'Brazzaville, Republic of the Congo',
  'Africa/Ceuta': 'Ceuta, Spain',
  'Africa/Douala': 'Douala, Cameroon',
  'Africa/Kinshasa': 'Kinshasa, Democratic Republic of the Congo',
  'Africa/Lagos': 'Lagos, Nigeria',
  'Africa/Libreville': 'Libreville, Gabon',
  'Africa/Luanda': 'Luanda, Angola',
  'Africa/Malabo': 'Malabo, Equatorial Guinea',
  'Africa/Ndjamena': 'Ndjamena, Chad',
  'Africa/Niamey': 'Niamey, Niger',
  'Africa/Porto-Novo': 'Porto-Novo, Benin',
  'Africa/Tunis': 'Tunis, Tunisia',
  'Africa/Windhoek': 'Windhoek, Namibia',
  'Africa/Blantyre': 'Blantyre, Malawi',
  'Africa/Bujumbura': 'Bujumbura, Burundi',
  'Africa/Cairo': 'Cairo, Egypt',
  'Africa/Gaborone': 'Gaborone, Botswana',
  'Africa/Harare': 'Harare, Zimbabwe',
  'Africa/Johannesburg': 'Johannesburg, South Africa',
  'Africa/Juba': 'Juba, South Sudan',
  'Africa/Khartoum': 'Khartoum, Sudan',
  'Africa/Kigali': 'Kigali, Rwanda',
  'Africa/Lubumbashi': 'Lubumbashi, Democratic Republic of the Congo',
  'Africa/Lusaka': 'Lusaka, Zambia',
  'Africa/Maputo': 'Maputo, Mozambique',
  'Africa/Maseru': 'Maseru, Lesotho',
  'Africa/Mbabane': 'Mbabane, Eswatini',
  'Africa/Tripoli': 'Tripoli, Libya',
  'Africa/Addis_Ababa': 'Addis Ababa, Ethiopia',
  'Africa/Asmera': 'Asmara, Eritrea',
  'Africa/Dar_es_Salaam': 'Dar es Salaam, Tanzania',
  'Africa/Djibouti': 'Djibouti',
  'Africa/Kampala': 'Kampala, Uganda',
  'Africa/Mogadishu': 'Mogadishu, Somalia',
  'Africa/Nairobi': 'Nairobi, Kenya',

  'Asia/Jerusalem': 'Jerusalem, Israel',
  'Asia/Beirut': 'Beirut, Lebanon',
  'Asia/Damascus': 'Damascus, Syria',
  'Asia/Amman': 'Amman, Jordan',
  'Asia/Nicosia': 'Nicosia, Cyprus',
  'Asia/Famagusta': 'Famagusta, Cyprus',
  'Asia/Gaza': 'Gaza, Palestine',
  'Asia/Hebron': 'Hebron, Palestine',
  'Asia/Baghdad': 'Baghdad, Iraq',
  'Asia/Kuwait': 'Kuwait City, Kuwait',
  'Asia/Riyadh': 'Riyadh, Saudi Arabia',
  'Asia/Bahrain': 'Bahrain',
  'Asia/Qatar': 'Qatar',
  'Asia/Aden': 'Aden, Yemen',
  'Asia/Dubai': 'Dubai, United Arab Emirates',
  'Asia/Muscat': 'Muscat, Oman',
  'Asia/Tehran': 'Tehran, Iran',

  'Asia/Yekaterinburg': 'Yekaterinburg, Russia',
  'Asia/Tbilisi': 'Tbilisi, Georgia',
  'Asia/Yerevan': 'Yerevan, Armenia',
  'Asia/Baku': 'Baku, Azerbaijan',
  'Asia/Kabul': 'Kabul, Afghanistan',
  'Asia/Ashgabat': 'Ashgabat, Turkmenistan',
  'Asia/Dushanbe': 'Dushanbe, Tajikistan',
  'Asia/Tashkent': 'Tashkent, Uzbekistan',
  'Asia/Samarkand': 'Samarkand, Uzbekistan',
  'Asia/Bishkek': 'Bishkek, Kyrgyzstan',
  'Asia/Almaty': 'Almaty, Kazakhstan',
  'Asia/Qostanay': 'Qostanay, Kazakhstan',
  'Asia/Qyzylorda': 'Qyzylorda, Kazakhstan',
  'Asia/Aqtobe': 'Aqtobe, Kazakhstan',
  'Asia/Aqtau': 'Aqtau, Kazakhstan',
  'Asia/Atyrau': 'Atyrau, Kazakhstan',
  'Asia/Oral': 'Oral, Kazakhstan',
  'Asia/Karachi': 'Karachi, Pakistan',
  'Asia/Omsk': 'Omsk, Russia',

  'Asia/Calcutta': 'Kolkata, India',
  'Asia/Colombo': 'Colombo, Sri Lanka',
  'Asia/Katmandu': 'Kathmandu, Nepal',
  'Asia/Dhaka': 'Dhaka, Bangladesh',
  'Asia/Thimphu': 'Thimphu, Bhutan',
  'Asia/Urumqi': 'Urumqi, China',

  'Asia/Rangoon': 'Rangoon, Myanmar',
  'Asia/Bangkok': 'Bangkok, Thailand',
  'Asia/Saigon': 'Hanoi, Vietnam',
  'Asia/Phnom_Penh': 'Phnom Penh, Cambodia',
  'Asia/Vientiane': 'Vientiane, Laos',
  'Asia/Jakarta': 'Jakarta, Indonesia',
  'Asia/Pontianak': 'Pontianak, Indonesia',
  'Asia/Krasnoyarsk': 'Krasnoyarsk, Russia',
  'Asia/Novokuznetsk': 'Novokuznetsk, Russia',
  'Asia/Novosibirsk': 'Novosibirsk, Russia',
  'Asia/Barnaul': 'Barnaul, Russia',
  'Asia/Tomsk': 'Tomsk, Russia',
  'Asia/Hovd': 'Hovd, Mongolia',

  'Asia/Shanghai': 'Shanghai, China',
  'Asia/Hong_Kong': 'Hong Kong',
  'Asia/Macau': 'Macau',
  'Asia/Taipei': 'Taipei, Taiwan',
  'Asia/Manila': 'Manila, Philippines',
  'Asia/Singapore': 'Singapore',
  'Asia/Kuala_Lumpur': 'Kuala Lumpur, Malaysia',
  'Asia/Kuching': 'Kuching, Malaysia',
  'Asia/Brunei': 'Brunei',
  'Asia/Makassar': 'Makassar, Indonesia',
  'Asia/Irkutsk': 'Irkutsk, Russia',
  'Asia/Chita': 'Chita, Russia',
  'Asia/Ulaanbaatar': 'Ulaanbaatar, Mongolia',
  'Asia/Pyongyang': 'Pyongyang, North Korea',
  'Asia/Seoul': 'Seoul, South Korea',
  'Asia/Tokyo': 'Tokyo, Japan',
  'Asia/Dili': 'Dili, East Timor',
  'Asia/Jayapura': 'Jayapura, Indonesia',
  'Asia/Yakutsk': 'Yakutsk, Russia',
  'Asia/Khandyga': 'Khandyga, Russia',

  'Asia/Vladivostok': 'Vladivostok, Russia',
  'Asia/Ust-Nera': 'Ust-Nera, Russia',
  'Asia/Magadan': 'Magadan, Russia',
  'Asia/Sakhalin': 'Sakhalin, Russia',
  'Asia/Srednekolymsk': 'Srednekolymsk, Russia',
  'Asia/Kamchatka': 'Kamchatka, Russia',
  'Asia/Anadyr': 'Anadyr, Russia',
  'Australia/Perth': 'Perth, Australia',
  'Australia/Eucla': 'Eucla, Australia',
  'Australia/Darwin': 'Darwin, Australia',
  'Australia/Adelaide': 'Adelaide, Australia',
  'Australia/Broken_Hill': 'Broken Hill, Australia',
  'Australia/Brisbane': 'Brisbane, Australia',
  'Australia/Lindeman': 'Lindeman, Australia',
  'Australia/Sydney': 'Sydney, Australia',
  'Australia/Melbourne': 'Melbourne, Australia',
  'Australia/Hobart': 'Hobart, Australia',
  'Australia/Lord_Howe': 'Lord Howe Island, Australia',
  'Pacific/Port_Moresby': 'Port Moresby, Papua New Guinea',
  'Pacific/Truk': 'Chuuk, Micronesia',
  'Pacific/Guam': 'Guam',
  'Pacific/Saipan': 'Saipan, Northern Mariana Islands',
  'Pacific/Palau': 'Palau',
  'Pacific/Guadalcanal': 'Guadalcanal, Solomon Islands',
  'Pacific/Ponape': 'Pohnpei, Micronesia',
  'Pacific/Kosrae': 'Kosrae, Micronesia',
  'Pacific/Noumea': 'Noumea, New Caledonia',
  'Pacific/Efate': 'Efate, Vanuatu',
  'Pacific/Norfolk': 'Norfolk Island',
  'Pacific/Fiji': 'Fiji',
  'Pacific/Funafuti': 'Funafuti, Tuvalu',
  'Pacific/Nauru': 'Nauru',
  'Pacific/Tarawa': 'Tarawa, Kiribati',
  'Pacific/Majuro': 'Majuro, Marshall Islands',
  'Pacific/Kwajalein': 'Kwajalein, Marshall Islands',
  'Pacific/Wake': 'Wake Island',
  'Pacific/Wallis': 'Wallis and Futuna',
  'Pacific/Auckland': 'Auckland, New Zealand',
  'Antarctica/McMurdo': 'McMurdo, Antarctica',
  'Pacific/Chatham': 'Chatham Islands, New Zealand',
  'Pacific/Enderbury': 'Enderbury, Kiribati',
  'Pacific/Fakaofo': 'Fakaofo, Tokelau',
  'Pacific/Tongatapu': 'Tongatapu, Tonga',
  'Pacific/Apia': 'Apia, Samoa',
  'Pacific/Kiritimati': 'Kiritimati, Kiribati',

  'Pacific/Honolulu': 'Honolulu, Hawaii',
  'Pacific/Rarotonga': 'Rarotonga, Cook Islands',
  'Pacific/Tahiti': 'Tahiti, French Polynesia',
  'Pacific/Marquesas': 'Marquesas Islands, French Polynesia',
  'Pacific/Gambier': 'Gambier Islands, French Polynesia',
  'Pacific/Pitcairn': 'Pitcairn Islands',
  'Pacific/Easter': 'Easter Island, Chile',
  'Pacific/Galapagos': 'Galapagos Islands, Ecuador',
  'Pacific/Pago_Pago': 'Pago Pago, American Samoa',
  'Pacific/Midway': 'Midway Atoll',
  'Pacific/Niue': 'Niue',
  'Pacific/Bougainville': 'Bougainville, Papua New Guinea',

  'Antarctica/Palmer': 'Palmer Station',
  'Antarctica/Rothera': 'Rothera Station',
  'Antarctica/Syowa': 'Syowa Station',
  'Antarctica/Mawson': 'Mawson Station',
  'Antarctica/Vostok': 'Vostok Station',
  'Antarctica/Davis': 'Davis Station',
  'Antarctica/Casey': 'Casey Station',
  'Antarctica/DumontDUrville': "Dumont d'Urville Station",
  'Antarctica/Troll': 'Troll Station',
  'Antarctica/Macquarie': 'Macquarie Island',

  'Indian/Maldives': 'Maldives',
  'Indian/Chagos': 'Chagos Archipelago',
  'Indian/Mahe': 'Mahe, Seychelles',
  'Indian/Mauritius': 'Mauritius',
  'Indian/Reunion': 'Reunion',
  'Indian/Antananarivo': 'Antananarivo, Madagascar',
  'Indian/Comoro': 'Comoro Islands',
  'Indian/Mayotte': 'Mayotte',
  'Indian/Kerguelen': 'Kerguelen Islands',
  'Indian/Christmas': 'Christmas Island',
  'Indian/Cocos': 'Cocos Islands',
};

export const TIMEZONE_LABEL_TO_VALUE = Object.entries(TIMEZONE_LABELS).reduce(
  (prev, [key, value]) => {
    prev[value] = key;

    return prev;
  },
  {} as Record<string, string>
);

const SORTED_LABEL_LIST = Object.keys(TIMEZONE_LABEL_TO_VALUE).sort();

export const GROUPED_TIMEZONES = [
  {
    group: 'United States & Canada',
    timezones: ['America/Los_Angeles', 'America/Denver', 'America/Chicago', 'America/New_York'],
  },
  {
    group: 'North America',
    timezones: [
      'America/Adak',
      'America/Anchorage',
      'America/Boise',
      'America/Phoenix',
      'America/Detroit',
      'America/Indianapolis',
      'America/Indiana/Knox',
      'America/Indiana/Marengo',
      'America/Indiana/Petersburg',
      'America/Indiana/Tell_City',
      'America/Indiana/Vevay',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Louisville',
      'America/Kentucky/Monticello',
      'America/North_Dakota/Beulah',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/Menominee',
      'America/Metlakatla',
      'America/Nome',
      'America/Juneau',
      'America/Sitka',
      'America/Yakutat',
    ],
  },
  {
    group: 'Canada',
    timezones: [
      'America/Vancouver',
      'America/Whitehorse',
      'America/Dawson',
      'America/Dawson_Creek',
      'America/Fort_Nelson',
      'America/Creston',
      'America/Edmonton',
      'America/Cambridge_Bay',
      'America/Inuvik',
      'America/Regina',
      'America/Swift_Current',
      'America/Winnipeg',
      'America/Rankin_Inlet',
      'America/Resolute',
      'America/Coral_Harbour',
      'America/Toronto',
      'America/Iqaluit',
      'America/Moncton',
      'America/Halifax',
      'America/Glace_Bay',
      'America/Goose_Bay',
      'America/Blanc-Sablon',
      'America/St_Johns',
    ],
  },
  {
    group: 'Mexico',
    timezones: [
      'America/Tijuana',
      'America/Hermosillo',
      'America/Mazatlan',
      'America/Chihuahua',
      'America/Ojinaga',
      'America/Ciudad_Juarez',
      'America/Monterrey',
      'America/Matamoros',
      'America/Mexico_City',
      'America/Bahia_Banderas',
      'America/Merida',
      'America/Cancun',
    ],
  },
  {
    group: 'Central America',
    timezones: [
      'America/Belize',
      'America/Guatemala',
      'America/Tegucigalpa',
      'America/El_Salvador',
      'America/Managua',
      'America/Costa_Rica',
      'America/Panama',
    ],
  },
  {
    group: 'Caribbean',
    timezones: [
      'America/Havana',
      'America/Nassau',
      'America/Grand_Turk',
      'America/Jamaica',
      'America/Cayman',
      'America/Port-au-Prince',
      'America/Santo_Domingo',
      'America/Puerto_Rico',
      'America/Anguilla',
      'America/Antigua',
      'America/Montserrat',
      'America/Guadeloupe',
      'America/Dominica',
      'America/Martinique',
      'America/St_Lucia',
      'America/St_Vincent',
      'America/Barbados',
      'America/Grenada',
      'America/Port_of_Spain',
      'America/St_Kitts',
      'America/St_Barthelemy',
      'America/Lower_Princes',
      'America/Marigot',
      'America/Aruba',
      'America/Curacao',
      'America/Kralendijk',
      'America/Tortola',
      'America/St_Thomas',
    ],
  },
  {
    group: 'South America',
    timezones: [
      'America/Caracas',
      'America/Guyana',
      'America/Paramaribo',
      'America/Cayenne',
      'America/Bogota',
      'America/Guayaquil',
      'America/Lima',
      'America/La_Paz',
      'America/Manaus',
      'America/Boa_Vista',
      'America/Porto_Velho',
      'America/Rio_Branco',
      'America/Eirunepe',
      'America/Cuiaba',
      'America/Campo_Grande',
      'America/Santarem',
      'America/Araguaina',
      'America/Belem',
      'America/Fortaleza',
      'America/Recife',
      'America/Maceio',
      'America/Bahia',
      'America/Sao_Paulo',
      'America/Santiago',
      'America/Punta_Arenas',
      'America/Asuncion',
      'America/Buenos_Aires',
      'America/Cordoba',
      'America/Jujuy',
      'America/Argentina/Tucuman',
      'America/Catamarca',
      'America/Argentina/La_Rioja',
      'America/Argentina/San_Juan',
      'America/Mendoza',
      'America/Argentina/San_Luis',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Ushuaia',
      'America/Argentina/Salta',
      'America/Montevideo',
      'America/Coyhaique',
      'America/Noronha',
    ],
  },
  {
    group: 'Atlantic',
    timezones: [
      'America/Scoresbysund',
      'America/Godthab',
      'America/Miquelon',
      'America/Thule',
      'America/Danmarkshavn',
      'Atlantic/Azores',
      'Atlantic/Cape_Verde',
      'Atlantic/South_Georgia',
      'Atlantic/Stanley',
      'Atlantic/Bermuda',
      'Atlantic/St_Helena',
    ],
  },
  {
    group: 'Europe',
    timezones: [
      'Atlantic/Reykjavik',
      'Europe/Dublin',
      'Europe/London',
      'Europe/Lisbon',
      'Atlantic/Madeira',
      'Atlantic/Canary',
      'Atlantic/Faeroe',
      'Europe/Guernsey',
      'Europe/Jersey',
      'Europe/Isle_of_Man',
      'Europe/Paris',
      'Europe/Brussels',
      'Europe/Amsterdam',
      'Europe/Luxembourg',
      'Europe/Monaco',
      'Europe/Berlin',
      'Europe/Zurich',
      'Europe/Vaduz',
      'Europe/Rome',
      'Europe/Vatican',
      'Europe/San_Marino',
      'Europe/Madrid',
      'Europe/Andorra',
      'Europe/Gibraltar',
      'Europe/Malta',
      'Europe/Vienna',
      'Europe/Prague',
      'Europe/Bratislava',
      'Europe/Budapest',
      'Europe/Ljubljana',
      'Europe/Zagreb',
      'Europe/Sarajevo',
      'Europe/Podgorica',
      'Europe/Belgrade',
      'Europe/Skopje',
      'Europe/Tirane',
      'Europe/Warsaw',
      'Europe/Copenhagen',
      'Europe/Stockholm',
      'Europe/Oslo',
      'Arctic/Longyearbyen',
      'Europe/Mariehamn',
      'Europe/Busingen',
      'Europe/Bucharest',
      'Europe/Chisinau',
      'Europe/Sofia',
      'Europe/Athens',
      'Europe/Nicosia',
      'Europe/Helsinki',
      'Europe/Tallinn',
      'Europe/Riga',
      'Europe/Vilnius',
      'Europe/Kiev',
      'Europe/Simferopol',
      'Europe/Istanbul',
      'Europe/Kaliningrad',
      'Europe/Minsk',
      'Europe/Moscow',
      'Europe/Kirov',
      'Europe/Volgograd',
      'Europe/Astrakhan',
      'Europe/Saratov',
      'Europe/Ulyanovsk',
      'Europe/Samara',
    ],
  },
  {
    group: 'Africa',
    timezones: [
      'Africa/Casablanca',
      'Africa/El_Aaiun',
      'Africa/Abidjan',
      'Africa/Accra',
      'Africa/Bamako',
      'Africa/Banjul',
      'Africa/Bissau',
      'Africa/Conakry',
      'Africa/Dakar',
      'Africa/Freetown',
      'Africa/Lome',
      'Africa/Monrovia',
      'Africa/Nouakchott',
      'Africa/Ouagadougou',
      'Africa/Sao_Tome',
      'Africa/Algiers',
      'Africa/Bangui',
      'Africa/Brazzaville',
      'Africa/Ceuta',
      'Africa/Douala',
      'Africa/Kinshasa',
      'Africa/Lagos',
      'Africa/Libreville',
      'Africa/Luanda',
      'Africa/Malabo',
      'Africa/Ndjamena',
      'Africa/Niamey',
      'Africa/Porto-Novo',
      'Africa/Tunis',
      'Africa/Windhoek',
      'Africa/Blantyre',
      'Africa/Bujumbura',
      'Africa/Cairo',
      'Africa/Gaborone',
      'Africa/Harare',
      'Africa/Johannesburg',
      'Africa/Juba',
      'Africa/Khartoum',
      'Africa/Kigali',
      'Africa/Lubumbashi',
      'Africa/Lusaka',
      'Africa/Maputo',
      'Africa/Maseru',
      'Africa/Mbabane',
      'Africa/Tripoli',
      'Africa/Addis_Ababa',
      'Africa/Asmera',
      'Africa/Dar_es_Salaam',
      'Africa/Djibouti',
      'Africa/Kampala',
      'Africa/Mogadishu',
      'Africa/Nairobi',
    ],
  },
  {
    group: 'Middle East',
    timezones: [
      'Asia/Jerusalem',
      'Asia/Beirut',
      'Asia/Damascus',
      'Asia/Amman',
      'Asia/Nicosia',
      'Asia/Famagusta',
      'Asia/Gaza',
      'Asia/Hebron',
      'Asia/Baghdad',
      'Asia/Kuwait',
      'Asia/Riyadh',
      'Asia/Bahrain',
      'Asia/Qatar',
      'Asia/Aden',
      'Asia/Dubai',
      'Asia/Muscat',
      'Asia/Tehran',
    ],
  },
  {
    group: 'Central Asia',
    timezones: [
      'Asia/Yekaterinburg',
      'Asia/Tbilisi',
      'Asia/Yerevan',
      'Asia/Baku',
      'Asia/Kabul',
      'Asia/Ashgabat',
      'Asia/Dushanbe',
      'Asia/Tashkent',
      'Asia/Samarkand',
      'Asia/Bishkek',
      'Asia/Almaty',
      'Asia/Qostanay',
      'Asia/Qyzylorda',
      'Asia/Aqtobe',
      'Asia/Aqtau',
      'Asia/Atyrau',
      'Asia/Oral',
      'Asia/Karachi',
      'Asia/Omsk',
    ],
  },
  {
    group: 'South Asia',
    timezones: [
      'Asia/Calcutta',
      'Asia/Colombo',
      'Asia/Katmandu',
      'Asia/Dhaka',
      'Asia/Thimphu',
      'Asia/Urumqi',
    ],
  },
  {
    group: 'Southeast Asia',
    timezones: [
      'Asia/Rangoon',
      'Asia/Bangkok',
      'Asia/Saigon',
      'Asia/Phnom_Penh',
      'Asia/Vientiane',
      'Asia/Jakarta',
      'Asia/Pontianak',
      'Asia/Krasnoyarsk',
      'Asia/Novokuznetsk',
      'Asia/Novosibirsk',
      'Asia/Barnaul',
      'Asia/Tomsk',
      'Asia/Hovd',
    ],
  },
  {
    group: 'East Asia',
    timezones: [
      'Asia/Shanghai',
      'Asia/Hong_Kong',
      'Asia/Macau',
      'Asia/Taipei',
      'Asia/Manila',
      'Asia/Singapore',
      'Asia/Kuala_Lumpur',
      'Asia/Kuching',
      'Asia/Brunei',
      'Asia/Makassar',
      'Asia/Irkutsk',
      'Asia/Chita',
      'Asia/Ulaanbaatar',
      'Asia/Pyongyang',
      'Asia/Seoul',
      'Asia/Tokyo',
      'Asia/Dili',
      'Asia/Jayapura',
      'Asia/Yakutsk',
      'Asia/Khandyga',
    ],
  },
  {
    group: 'Australia & Pacific',
    timezones: [
      'Asia/Vladivostok',
      'Asia/Ust-Nera',
      'Asia/Magadan',
      'Asia/Sakhalin',
      'Asia/Srednekolymsk',
      'Asia/Kamchatka',
      'Asia/Anadyr',
      'Australia/Perth',
      'Australia/Eucla',
      'Australia/Darwin',
      'Australia/Adelaide',
      'Australia/Broken_Hill',
      'Australia/Brisbane',
      'Australia/Lindeman',
      'Australia/Sydney',
      'Australia/Melbourne',
      'Australia/Hobart',
      'Australia/Lord_Howe',
      'Pacific/Port_Moresby',
      'Pacific/Truk',
      'Pacific/Guam',
      'Pacific/Saipan',
      'Pacific/Palau',
      'Pacific/Guadalcanal',
      'Pacific/Ponape',
      'Pacific/Kosrae',
      'Pacific/Noumea',
      'Pacific/Efate',
      'Pacific/Norfolk',
      'Pacific/Fiji',
      'Pacific/Funafuti',
      'Pacific/Nauru',
      'Pacific/Tarawa',
      'Pacific/Majuro',
      'Pacific/Kwajalein',
      'Pacific/Wake',
      'Pacific/Wallis',
      'Pacific/Auckland',
      'Antarctica/McMurdo',
      'Pacific/Chatham',
      'Pacific/Enderbury',
      'Pacific/Fakaofo',
      'Pacific/Tongatapu',
      'Pacific/Apia',
      'Pacific/Kiritimati',
    ],
  },
  {
    group: 'Pacific Islands',
    timezones: [
      'Pacific/Honolulu',
      'Pacific/Rarotonga',
      'Pacific/Tahiti',
      'Pacific/Marquesas',
      'Pacific/Gambier',
      'Pacific/Pitcairn',
      'Pacific/Easter',
      'Pacific/Galapagos',
      'Pacific/Pago_Pago',
      'Pacific/Midway',
      'Pacific/Niue',
      'Pacific/Bougainville',
    ],
  },
  {
    group: 'Antarctica',
    timezones: [
      'Antarctica/Palmer',
      'Antarctica/Rothera',
      'Antarctica/Syowa',
      'Antarctica/Mawson',
      'Antarctica/Vostok',
      'Antarctica/Davis',
      'Antarctica/Casey',
      'Antarctica/DumontDUrville',
      'Antarctica/Troll',
      'Antarctica/Macquarie',
    ],
  },
  {
    group: 'Indian Ocean',
    timezones: [
      'Indian/Maldives',
      'Indian/Chagos',
      'Indian/Mahe',
      'Indian/Mauritius',
      'Indian/Reunion',
      'Indian/Antananarivo',
      'Indian/Comoro',
      'Indian/Mayotte',
      'Indian/Kerguelen',
      'Indian/Christmas',
      'Indian/Cocos',
    ],
  },
];

const getFraction = (val: number): number => val - Math.floor(val);

// Accepts timezone and returns offset formatted as "GMT[+-]00:00"
const getGMTOffset = (timeZone: string) => {
  try {
    const offsetInMinutes = dayjs().tz(timeZone).utcOffset(); // returns offset * 60

    if (Number.isNaN(offsetInMinutes)) return '';

    const offset = offsetInMinutes / 60;

    if (offset === 0) return 'GMT';

    const flooredOffset = offset < 0 ? Math.ceil(offset) : Math.floor(offset);
    const fraction = Math.floor(getFraction(offset) * 60);

    return `GMT${flooredOffset > 0 ? '+' : '-'}${Math.abs(flooredOffset)
      .toString(10)
      .padStart(2, '0')}:${fraction.toString(10).padStart(2, '0')}`;
  } catch {
    return '';
  }
};

export const TIMEZONE_OFFSETS: Record<string, string> = Object.keys(TIMEZONE_LABELS).reduce(
  (prev, curr) => {
    prev[curr] = getGMTOffset(curr);

    return prev;
  },
  {} as Record<string, string>
);

export const TIMEZONE_GROUPS_FOR_LISTING: (
  | { type: 'timezone'; value: string }
  | { type: 'header'; label: string }
)[] = GROUPED_TIMEZONES.flatMap((timezoneGroup) => [
  { type: 'header' as const, label: timezoneGroup.group },
  ...timezoneGroup.timezones.map((timezone) => ({ type: 'timezone' as const, value: timezone })),
]);

export function searchByLabel(query: string): string[] {
  if (!query) return [];

  // Lower bound binary search to find the first possible match
  let low = 0;
  let high = SORTED_LABEL_LIST.length;
  while (low < high) {
    const mid = Math.floor((low + high) / 2);
    if (SORTED_LABEL_LIST[mid] < query) {
      low = mid + 1;
    } else {
      high = mid;
    }
  }

  const results: string[] = [];

  // Collect all items starting with the prefix
  for (let i = low; i < SORTED_LABEL_LIST.length; i += 1) {
    const item = SORTED_LABEL_LIST[i];
    if (item.startsWith(query)) results.push(item);
    else break; // stop when prefix no longer matches
  }

  return results;
}

export function fuzzySearchByLabel(query: string): string[] {
  if (!query) return [];

  return SORTED_LABEL_LIST.filter((label) => label.toLowerCase().includes(query.toLowerCase()));
}
